// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `map_value`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String> hello({required String a}) =>
    RustLib.instance.api.crateApiSimpleHello(a: a);

Future<DynamicValue> quickJsonDecode({required String jsonStr}) =>
    RustLib.instance.api.crateApiSimpleQuickJsonDecode(jsonStr: jsonStr);

Future<void> pureJsonParse({required String jsonStr}) =>
    RustLib.instance.api.crateApiSimplePureJsonParse(jsonStr: jsonStr);

Future<void> pureJsonParseBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiSimplePureJsonParseBytes(bytes: bytes);

Future<SimpleUser> parseUserStruct({required String jsonStr}) =>
    RustLib.instance.api.crateApiSimpleParseUserStruct(jsonStr: jsonStr);

Stream<SimpleUser> parseUserStream({required List<int> jsonBytes}) =>
    RustLib.instance.api.crateApiSimpleParseUserStream(jsonBytes: jsonBytes);

@freezed
sealed class DynamicValue with _$DynamicValue {
  const DynamicValue._();

  const factory DynamicValue.null_() = DynamicValue_Null;
  const factory DynamicValue.bool(bool field0) = DynamicValue_Bool;
  const factory DynamicValue.number(double field0) = DynamicValue_Number;
  const factory DynamicValue.string(String field0) = DynamicValue_String;
  const factory DynamicValue.list(List<DynamicValue> field0) =
      DynamicValue_List;
  const factory DynamicValue.map(List<(String, DynamicValue)> field0) =
      DynamicValue_Map;
}

class SimpleUser {
  final int id;
  final String name;
  final String email;

  const SimpleUser({required this.id, required this.name, required this.email});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleUser &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          email == other.email;
}
